#!/bin/bash

## Put this script into /usr/bin/ to be able to call this as a command.
## Example use: "pi@raspberrypi:~ $ mcaverage LAST" or "pi@raspberrypi:~ $ mcaverage CURRENT" 

cd /home/annika/Dokument/MasterMcVoiceIt_PiSoftware/ # Edit this if the java program is located elsewhere
java McAverage $*
